services:
  redis:
    container_name: deepersleeper_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - deepersleeper_network
  
  api:
    build:
      context: ./api
    container_name: deepersleeper_api
    ports:
      - "8000:8000"
    restart: always
    networks:
      - deepersleeper_network
    env_file:
      - ./api/.env
    depends_on:
      - redis

  web:
    build:
      context: ./web
    container_name: deepersleeper_web
    ports:
      - "3000:3000"
    restart: always
    networks:
      - deepersleeper_network
    env_file:
      - ./web/.env
    depends_on:
      - api

networks:
  deepersleeper_network:
    driver: bridge