services:
  api:
    build:
      context: ./api
      target: ${NODE_ENV}
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: deepersleeper_api
    ports:
      - "8000:8000"
    restart: always
    networks:
      - deepersleeper_network
    env_file:
      - ./api/.env

  web:
    build:
      context: ./web
      target: ${NODE_ENV}
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: deepersleeper_web
    ports:
      - ${PORT_MAPPING}
    restart: always
    networks:
      - deepersleeper_network
    env_file:
      - ./web/.env
    depends_on:
      - api

networks:
  deepersleeper_network:
    driver: bridge