services:
  redis:
    container_name: deepersleeper_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - deepersleeper_network
  
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: deepersleeper_api
    ports:
      - "8000:8000"
    restart: always
    networks:
      - deepersleeper_network
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: deepersleeper_web
    ports:
      - "3000:3000"
    restart: always
    networks:
      - deepersleeper_network
    depends_on:
      - api

networks:
  deepersleeper_network:
    driver: bridge